<?php

use App\Controllers\AuthController;
use App\Controllers\ArchiveController;
use App\Controllers\DashboardController;
use App\Controllers\NoticeController;
use App\Controllers\ProfileController;
use App\Controllers\PublicNoticeController;
use App\Controllers\UserController;
use App\Controllers\VerificationController;
use App\Controllers\WorkflowValidationController;

router()->get('/', [PublicNoticeController::class, 'index']);
router()->get('/public/notices/{id}', [PublicNoticeController::class, 'show']);
router()->get('/public/notices/{id}/file', [PublicNoticeController::class, 'file']);
router()->get('/login', [AuthController::class, 'showLogin']);
router()->post('/login', [AuthController::class, 'login']);
router()->get('/register', [AuthController::class, 'showRegister']);
router()->post('/register', [AuthController::class, 'register']);
router()->post('/logout', [AuthController::class, 'logout']);
router()->get('/verify', [VerificationController::class, 'showVerify']);
router()->post('/verify', [VerificationController::class, 'verify']);
router()->get('/email-change/verify', [VerificationController::class, 'verifyEmailChange']);
router()->get('/dashboard', [DashboardController::class, 'index']);
router()->get('/dashboard/competitive-bidding', [DashboardController::class, 'competitiveBidding']);
router()->get('/dashboard/svp', [DashboardController::class, 'svp']);
router()->get('/users', [UserController::class, 'index']);
router()->post('/users/{id}/update', [UserController::class, 'update']);
router()->post('/users/{id}/toggle-active', [UserController::class, 'toggleActive']);
router()->post('/users/{id}/delete', [UserController::class, 'destroy']);
router()->get('/profile', [ProfileController::class, 'show']);
router()->post('/profile', [ProfileController::class, 'update']);
router()->post('/profile/password', [ProfileController::class, 'updatePassword']);
router()->get('/notices', [NoticeController::class, 'index']);
router()->get('/procurements/create', [NoticeController::class, 'create']);
router()->get('/procurements/create/competitive-bidding', [NoticeController::class, 'createCompetitiveBidding']);
router()->post('/procurements/competitive-bidding', [NoticeController::class, 'storeCompetitiveBidding']);
router()->get('/procurements/create/svp', [NoticeController::class, 'createSvp']);
router()->post('/procurements/svp', [NoticeController::class, 'storeSvp']);
router()->get('/procurements/{id}/workflow/competitive-bidding', [NoticeController::class, 'showCompetitiveBidding']);
router()->get('/procurements/{id}/workflow/svp', [NoticeController::class, 'showSvp']);
router()->get('/notices/create', [NoticeController::class, 'create']);
router()->post('/notices', [NoticeController::class, 'store']);
router()->get('/notices/related/create', [NoticeController::class, 'createRelated']);
router()->post('/notices/related', [NoticeController::class, 'storeRelated']);
router()->get('/notices/{id}', [NoticeController::class, 'show']);
router()->get('/notices/{id}/file', [NoticeController::class, 'file']);
router()->post('/notices/{id}/svp/rfq', [NoticeController::class, 'saveSvpRfq']);
router()->post('/notices/{id}/svp/evaluation', [NoticeController::class, 'saveSvpEvaluation']);
router()->post('/notices/{id}/svp/canvass', [NoticeController::class, 'saveSvpCanvass']);
router()->post('/notices/{id}/svp/award', [NoticeController::class, 'addSvpAward']);
router()->post('/notices/{id}/svp/contract', [NoticeController::class, 'addSvpContract']);
router()->post('/notices/{id}/svp/ntp', [NoticeController::class, 'addSvpNtp']);
router()->get('/documents/{type}/{id}/file', [NoticeController::class, 'documentFile']);
router()->get('/public/documents/{type}/{id}/file', [PublicNoticeController::class, 'documentFile']);
router()->post('/notices/{id}/delete', [NoticeController::class, 'destroy']);
router()->post('/notices/{id}/archive', [ArchiveController::class, 'archive']);
router()->get('/api/workflow/eligible-bids', [WorkflowValidationController::class, 'eligibleBids']);
