USE `bps`;

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `email_change_requests`;
TRUNCATE TABLE `notices`;
TRUNCATE TABLE `users`;
SET FOREIGN_KEY_CHECKS = 1;

-- Password for all seeded users: Password123!
INSERT INTO `users` (
    `id`,
    `username`,
    `firstname`,
    `middle_initial`,
    `lastname`,
    `region`,
    `branch`,
    `password`,
    `role`,
    `email`,
    `verification_token`,
    `verification_code`,
    `token_expiry`,
    `is_verified`,
    `is_active`,
    `created_at`,
    `updated_at`
) VALUES
    (
        1,
        'admin.ncr',
        'Alicia',
        'M',
        'Reyes',
        'NCR',
        'NCR',
        '$2y$10$eiQoNjPX8lM109hwGGlmdeV.eBCnWLC.AjcNKCAlCSOrjP8rvLmR.',
        'admin',
        'admin.ncr@agency.gov.ph',
        NULL,
        NULL,
        NULL,
        1,
        1,
        NOW(),
        NOW()
    ),
    (
        2,
        'admin.region4',
        'Benjamin',
        'L',
        'Cruz',
        'Region IV',
        'Laguna Branch',
        '$2y$10$eiQoNjPX8lM109hwGGlmdeV.eBCnWLC.AjcNKCAlCSOrjP8rvLmR.',
        'admin',
        'admin.region4@agency.gov.ph',
        NULL,
        NULL,
        NULL,
        1,
        1,
        NOW(),
        NOW()
    ),
    (
        3,
        'author.ncr.central',
        'Carla',
        'S',
        'Dizon',
        'NCR',
        'Central District',
        '$2y$10$eiQoNjPX8lM109hwGGlmdeV.eBCnWLC.AjcNKCAlCSOrjP8rvLmR.',
        'author',
        'author.ncr.central@agency.gov.ph',
        NULL,
        NULL,
        NULL,
        1,
        1,
        NOW(),
        NOW()
    ),
    (
        4,
        'author.region4.laguna',
        'Daniel',
        'P',
        'Santos',
        'Region IV',
        'Laguna Branch',
        '$2y$10$eiQoNjPX8lM109hwGGlmdeV.eBCnWLC.AjcNKCAlCSOrjP8rvLmR.',
        'author',
        'author.region4.laguna@agency.gov.ph',
        NULL,
        NULL,
        NULL,
        1,
        1,
        NOW(),
        NOW()
    ),
    (
        5,
        'author.region7.cebu',
        'Elena',
        'R',
        'Garcia',
        'Region VII',
        'Cebu Branch',
        '$2y$10$eiQoNjPX8lM109hwGGlmdeV.eBCnWLC.AjcNKCAlCSOrjP8rvLmR.',
        'author',
        'author.region7.cebu@agency.gov.ph',
        NULL,
        NULL,
        NULL,
        1,
        1,
        NOW(),
        NOW()
    ),
    (
        6,
        'author.region1.union',
        'Francis',
        'T',
        'Mendoza',
        'Region I',
        'La Union Branch',
        '$2y$10$eiQoNjPX8lM109hwGGlmdeV.eBCnWLC.AjcNKCAlCSOrjP8rvLmR.',
        'author',
        'author.region1.union@agency.gov.ph',
        NULL,
        NULL,
        NULL,
        1,
        1,
        NOW(),
        NOW()
    ),
    (
        7,
        'pending.region3',
        'Grace',
        'N',
        'Flores',
        'Region III',
        'Bulacan Branch',
        '$2y$10$eiQoNjPX8lM109hwGGlmdeV.eBCnWLC.AjcNKCAlCSOrjP8rvLmR.',
        'author',
        'pending.region3@agency.gov.ph',
        NULL,
        '654321',
        DATE_ADD(NOW(), INTERVAL 15 MINUTE),
        0,
        0,
        NOW(),
        NOW()
    ),
    (
        8,
        'inactive.caraga',
        'Henry',
        'Q',
        'Aquino',
        'CARAGA',
        'CARAGA',
        '$2y$10$eiQoNjPX8lM109hwGGlmdeV.eBCnWLC.AjcNKCAlCSOrjP8rvLmR.',
        'author',
        'inactive.caraga@agency.gov.ph',
        NULL,
        NULL,
        NULL,
        1,
        0,
        NOW(),
        NOW()
    );

-- Active workflow set in NCR with full notice chain.
INSERT INTO `notices` (
    `id`,
    `title`,
    `reference_code`,
    `type`,
    `file_path`,
    `upload_date`,
    `start_date`,
    `end_date`,
    `uploaded_by`,
    `description`,
    `is_archived`,
    `status`,
    `region`,
    `branch`,
    `procurement_type`,
    `archived_at`
) VALUES
    (
        1001,
        'National ICT Infrastructure Upgrade 2026',
        'BPS-2026-001',
        'bid',
        'storage/uploads/notices/sample-bid-001.pdf',
        NOW(),
        DATE_SUB(NOW(), INTERVAL 5 DAY),
        DATE_ADD(NOW(), INTERVAL 20 DAY),
        3,
        'Active NCR bid notice used for public listing, workflow validation, and related notice creation.',
        0,
        'active',
        'NCR',
        'Central District',
        'competitive_bidding',
        NULL
    ),
    (
        1002,
        'Supplemental Bid Bulletin for ICT Infrastructure Upgrade',
        'BPS-2026-001',
        'sbb',
        'storage/uploads/notices/sample-sbb-001.pdf',
        NOW(),
        DATE_SUB(NOW(), INTERVAL 4 DAY),
        DATE_ADD(NOW(), INTERVAL 18 DAY),
        3,
        'Clarifications and amendments for the active ICT bidding opportunity.',
        0,
        'active',
        'NCR',
        'Central District',
        'competitive_bidding',
        NULL
    ),
    (
        1003,
        'BAC Resolution for ICT Infrastructure Upgrade',
        'BPS-2026-001',
        'resolution',
        'storage/uploads/notices/sample-resolution-001.pdf',
        NOW(),
        DATE_SUB(NOW(), INTERVAL 3 DAY),
        DATE_ADD(NOW(), INTERVAL 17 DAY),
        3,
        'Resolution attached to the active workflow set.',
        0,
        'active',
        'NCR',
        'Central District',
        'competitive_bidding',
        NULL
    ),
    (
        1004,
        'Notice of Award for ICT Infrastructure Upgrade',
        'BPS-2026-001',
        'award',
        'storage/uploads/notices/sample-award-001.pdf',
        NOW(),
        DATE_SUB(NOW(), INTERVAL 2 DAY),
        DATE_ADD(NOW(), INTERVAL 16 DAY),
        3,
        'Award notice within the active workflow set.',
        0,
        'active',
        'NCR',
        'Central District',
        'competitive_bidding',
        NULL
    ),
    (
        1005,
        'Contract for ICT Infrastructure Upgrade',
        'BPS-2026-001',
        'contract',
        'storage/uploads/notices/sample-contract-001.pdf',
        NOW(),
        DATE_SUB(NOW(), INTERVAL 1 DAY),
        DATE_ADD(NOW(), INTERVAL 15 DAY),
        3,
        'Contract notice within the active workflow set.',
        0,
        'active',
        'NCR',
        'Central District',
        'competitive_bidding',
        NULL
    ),
    (
        1006,
        'Notice to Proceed for ICT Infrastructure Upgrade',
        'BPS-2026-001',
        'proceed',
        'storage/uploads/notices/sample-proceed-001.pdf',
        NOW(),
        NOW(),
        DATE_ADD(NOW(), INTERVAL 14 DAY),
        3,
        'Proceed notice to complete the active procurement workflow.',
        0,
        'active',
        'NCR',
        'Central District',
        'competitive_bidding',
        NULL
    );

-- Pending notices for editing and owner permissions.
INSERT INTO `notices` (
    `id`,
    `title`,
    `reference_code`,
    `type`,
    `file_path`,
    `upload_date`,
    `start_date`,
    `end_date`,
    `uploaded_by`,
    `description`,
    `is_archived`,
    `status`,
    `region`,
    `branch`,
    `procurement_type`,
    `archived_at`
) VALUES
    (
        1101,
        'Laguna Branch Office Renovation 2026',
        'BPS-2026-010',
        'bid',
        'storage/uploads/notices/sample-bid-002.pdf',
        NOW(),
        DATE_ADD(NOW(), INTERVAL 5 DAY),
        DATE_ADD(NOW(), INTERVAL 25 DAY),
        4,
        'Pending Region IV notice reserved for edit and delete testing.',
        0,
        'pending',
        'Region IV',
        'Laguna Branch',
        'small_value_procurement',
        NULL
    ),
    (
        1102,
        'Cebu Warehouse Security Services 2026',
        'BPS-2026-011',
        'bid',
        'storage/uploads/notices/sample-bid-005.pdf',
        NOW(),
        DATE_ADD(NOW(), INTERVAL 2 DAY),
        DATE_ADD(NOW(), INTERVAL 18 DAY),
        5,
        'Pending Region VII notice using negotiated procurement.',
        0,
        'pending',
        'Region VII',
        'Cebu Branch',
        'negotiated_procurement',
        NULL
    );

-- Expired workflow set for archive-by-expiration checks.
INSERT INTO `notices` (
    `id`,
    `title`,
    `reference_code`,
    `type`,
    `file_path`,
    `upload_date`,
    `start_date`,
    `end_date`,
    `uploaded_by`,
    `description`,
    `is_archived`,
    `status`,
    `region`,
    `branch`,
    `procurement_type`,
    `archived_at`
) VALUES
    (
        1201,
        'Region I Grain Storage Expansion 2025',
        'BPS-2025-020',
        'bid',
        'storage/uploads/notices/sample-bid-003.pdf',
        NOW(),
        DATE_SUB(NOW(), INTERVAL 50 DAY),
        DATE_SUB(NOW(), INTERVAL 15 DAY),
        6,
        'Expired Region I bid notice retained to test historical and archival behaviors.',
        0,
        'expired',
        'Region I',
        'La Union Branch',
        'direct_acquisition',
        NULL
    ),
    (
        1202,
        'Resolution for Grain Storage Expansion',
        'BPS-2025-020',
        'resolution',
        'storage/uploads/notices/sample-resolution-003.pdf',
        NOW(),
        DATE_SUB(NOW(), INTERVAL 48 DAY),
        DATE_SUB(NOW(), INTERVAL 14 DAY),
        6,
        'Expired resolution record related to the Region I workflow set.',
        0,
        'expired',
        'Region I',
        'La Union Branch',
        'direct_acquisition',
        NULL
    );

-- Archived workflow set for restore testing.
INSERT INTO `notices` (
    `id`,
    `title`,
    `reference_code`,
    `type`,
    `file_path`,
    `upload_date`,
    `start_date`,
    `end_date`,
    `uploaded_by`,
    `description`,
    `is_archived`,
    `status`,
    `region`,
    `branch`,
    `procurement_type`,
    `archived_at`
) VALUES
    (
        1301,
        'Regional Fleet Maintenance Services 2025',
        'BPS-2025-030',
        'bid',
        'storage/uploads/notices/sample-bid-004.pdf',
        NOW(),
        DATE_SUB(NOW(), INTERVAL 40 DAY),
        DATE_ADD(NOW(), INTERVAL 10 DAY),
        2,
        'Archived bid notice used to verify grouped archive and unarchive actions.',
        1,
        'archived',
        'Region IV',
        'Laguna Branch',
        'repeat_order',
        DATE_SUB(NOW(), INTERVAL 3 DAY)
    ),
    (
        1302,
        'Resolution for Fleet Maintenance Services',
        'BPS-2025-030',
        'resolution',
        'storage/uploads/notices/sample-resolution-004.pdf',
        NOW(),
        DATE_SUB(NOW(), INTERVAL 38 DAY),
        DATE_ADD(NOW(), INTERVAL 9 DAY),
        2,
        'Archived resolution attached to the fleet maintenance workflow.',
        1,
        'archived',
        'Region IV',
        'Laguna Branch',
        'repeat_order',
        DATE_SUB(NOW(), INTERVAL 3 DAY)
    ),
    (
        1303,
        'Award for Fleet Maintenance Services',
        'BPS-2025-030',
        'award',
        'storage/uploads/notices/sample-award-004.pdf',
        NOW(),
        DATE_SUB(NOW(), INTERVAL 36 DAY),
        DATE_ADD(NOW(), INTERVAL 8 DAY),
        2,
        'Archived award document attached to the fleet maintenance workflow.',
        1,
        'archived',
        'Region IV',
        'Laguna Branch',
        'repeat_order',
        DATE_SUB(NOW(), INTERVAL 3 DAY)
    );

INSERT INTO `email_change_requests` (
    `id`,
    `user_id`,
    `current_email`,
    `new_email`,
    `token`,
    `status`,
    `created_at`,
    `expires_at`
) VALUES
    (
        2001,
        3,
        'author.ncr.central@agency.gov.ph',
        'author.ncr.central.updated@agency.gov.ph',
        'seed-email-change-token-101',
        'pending',
        NOW(),
        DATE_ADD(NOW(), INTERVAL 1 DAY)
    ),
    (
        2002,
        4,
        'author.region4.laguna@agency.gov.ph',
        'author.region4.laguna.completed@agency.gov.ph',
        'seed-email-change-token-102',
        'completed',
        NOW(),
        DATE_SUB(DATE_ADD(NOW(), INTERVAL 1 DAY), INTERVAL 12 HOUR)
    );
